quarkus.langchain4j.openai.chat-model.model-name=gpt-4o-mini
quarkus.langchain4j.skills.directories=classpath:skills
quarkus.native.resources.includes=skills/**

quarkus.langchain4j.log-responses=true
quarkus.langchain4j.log-requests=true
