quarkus.langchain4j.openai.chat-model.model-name=gpt-4o-mini
quarkus.langchain4j.skills.directories=src/main/resources/skills

quarkus.langchain4j.log-responses=true
quarkus.langchain4j.log-requests=true
