quarkus.langchain4j.timeout=60s

%openai.quarkus.langchain4j.openai.chat-model.temperature=0
%openai.quarkus.langchain4j.openai.model-name=gpt-4.1-nano
%openai.quarkus.langchain4j.openai.log-requests=true