---
# The format of this file is documented here:
# https://github.com/quarkusio/quarkus-github-bot#triage-issues
features: [ANALYZE_WORKFLOW_RUN_RESULTS]
workflowRunAnalysis:
  workflows: ["Build (on pull request)"]
