#!/usr/bin/env bash
set -e

# update the versions
mvn --settings .github/quarkus-ecosystem-maven-settings.xml -B versions:set-property -Dproperty=quarkus.version -DnewVersion=${QUARKUS_VERSION} -DgenerateBackupPoms=false
mvn --settings .github/quarkus-ecosystem-maven-settings.xml -B versions:set-property -Dproperty=version.io.quarkus -DnewVersion=${QUARKUS_VERSION} -DgenerateBackupPoms=false

# run the tests while skipping docs
mvn --settings .github/quarkus-ecosystem-maven-settings.xml -B clean install -Dquarkus.platform.group-id=io.quarkus -Dquarkus.platform.version=${QUARKUS_VERSION} -Dnative -Dquarkus.native.container-build=true --projects '!io.quarkiverse.langchain4j:quarkus-langchain4j-docs' --fail-at-end -e
