quarkus.datasource.devservices.image-name=pgvector/pgvector:pg17
movies.file=src/main/resources/movies.csv

# For the MovieIT
%prod.quarkus.langchain4j.hibernate.setup-vector-config=true
#quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY}