<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>io.quarkiverse.langchain4j</groupId>
		<artifactId>quarkus-langchain4j-sample-agent-registry-workflow</artifactId>
		<version>1.0-SNAPSHOT</version>
	</parent>
	<artifactId>quarkus-langchain4j-sample-registry-text-agent</artifactId>
	<name>Quarkus LangChain4j - Sample - Registry Text Agent</name>
	<dependencies>
		<dependency>
			<groupId>io.quarkiverse.langchain4j</groupId>
			<artifactId>quarkus-langchain4j-ollama</artifactId>
			<version>${quarkus-langchain4j.version}</version>
		</dependency>
		<dependency>
			<groupId>io.quarkiverse.langchain4j</groupId>
			<artifactId>quarkus-langchain4j-a2a-apicurio-registry</artifactId>
			<version>${quarkus-langchain4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.a2aproject.sdk</groupId>
			<artifactId>a2a-java-sdk-reference-jsonrpc</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest-jackson</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-smallrye-health</artifactId>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>io.quarkus</groupId>
				<artifactId>quarkus-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
