quarkus.langchain4j.log-requests=true

quarkus.langchain4j.mcp.generate-tool-provider.transport-type=http
quarkus.langchain4j.mcp.generate-tool-provider.url=http://localhost:8081/mcp/sse/

quarkus.http.port=8080

quarkus.langchain4j.timeout=30s

quarkus.oidc.provider=google
quarkus.oidc.client-id=${GOOGLE_CLIENT_ID}
quarkus.oidc.credentials.secret=${GOOGLE_CLIENT_SECRET}
quarkus.oidc.authentication.extra-params.scope=https://www.googleapis.com/auth/generative-language.retriever

quarkus.langchain4j.ai.gemini.log-requests=true
quarkus.langchain4j.ai.gemini.log-responses=true
