= AI Gemini

include::./includes/attributes.adoc[]

https://gemini.google.com/[Gemini] is a simpler platform designed for more broader audience than Vertex AI Gemini, including non-technical users.
It is a good first step for developers to get started on Gemini models.

== Using Gemini Models

To employ Gemini LLMs, integrate the following dependency into your project:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.langchain4j</groupId>
    <artifactId>quarkus-langchain4j-ai-gemini</artifactId>
    <version>{project-version}</version>
</dependency>
----

If no other LLM extension is installed, xref:ai-services.adoc[AI Services] will automatically utilize the configured Gemini model.

=== Configuration

Configuring Gemini models mandates an API key, obtainable by creating an account on the https://ai.google.dev/gemini-api/docs/api-key[Gemini platform].

The API key can be set in the `application.properties` file:

[source,properties,subs=attributes+]
----
quarkus.langchain4j.ai.gemini.api-key=...
----

TIP: Alternatively, leverage the `QUARKUS_LANGCHAIN4J_AI_GEMINI_API_KEY` environment variable.

=== Embedding Model

You can use the Gemini embedding model too.

[source, java]
----
@Inject
EmbeddingModel embeddingModel;
----

Several configuration properties are available:

include::includes/quarkus-langchain4j-ai-gemini.adoc[leveloffset=+1,opts=optional]
