= Enabling or Disabling AI Model Integrations

include::./includes/attributes.adoc[]
include::./includes/customization.adoc[]

By default, all AI provider integrations (e.g., OpenAI, HuggingFace, Azure OpenAI) are enabled. This means that live API calls are made to the respective providers when an AI service is invoked.

You can disable any provider at runtime using the corresponding configuration property:

- `quarkus.langchain4j.openai.enable-integration`
- `quarkus.langchain4j.huggingface.enable-integration`
- `quarkus.langchain4j.azure-openai.enable-integration`

Setting this property to `false` will prevent any live call to the model, and a call to the provider will result in a `dev.langchain4j.model.ModelDisabledException` being thrown.

NOTE: It disables the whole integration, so all the models provided by the extension are disabled.

In such cases, your xref:ai-services.adoc[AI Service] can leverage xref:guide-fault-tolerance.adoc[fault tolerance] mechanisms to handle this exception and provide a fallback response.

The following examples illustrate how to handle disabled integrations using fault-tolerant within AI services:

[source,java]
.Handling disabled integration separately from other error conditions
----
include::{examples-dir}/io/quarkiverse/langchain4j/samples/AiServiceWithFaultToleranceAndOnDisabledIntegration.java[]
----

[source,java]
.Handling only disabled integration
----
include::{examples-dir}/io/quarkiverse/langchain4j/samples/AiServiceWithFaultToleranceOnlyOnDisabledIntegration.java[]
----