= Milvus Store for Retrieval Augmented Generation (RAG)

include::./includes/attributes.adoc[]

When implementing Retrieval Augmented Generation (RAG), a robust document store is crucial. This guide demonstrates how to leverage a https://Milvus.io/[Milvus] database as the document store.


== Leveraging the Milvus embedding store

To make use of the Milvus embedding store, you'll need to include the following dependency:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.langchain4j</groupId>
    <artifactId>quarkus-langchain4j-milvus</artifactId>
</dependency>
----

This extension includes a dev service. Therefore, if you're operating in a container environment, a Milvus instance will automatically start in dev and test mode.

Upon installing the extension, you can use the Milvus document store with the following code:

[source,java]
----
include::{examples-dir}/io/quarkiverse/langchain4j/samples/IngestorExampleWithMilvus.java[]
----

NOTE: To get started, only one configuration property is required to be
set - `quarkus.langchain4j.milvus.dimension`, which specifies the dimension
of the embeddings that you're going to store and depends on the embedding
model.

To use a remote Milvus instance, you have to also set the host and port, in which case dev-services
will not start another instance:

[source, java]
----
quarkus.langchain4j.milvus.host=localhost
quarkus.langchain4j.milvus.port=19530
----

== Configuration Settings

Customize the behavior of the extension by exploring various configuration options:

include::includes/quarkus-langchain4j-milvus.adoc[leveloffset=+1,opts=optional]
