= Neo4j Store for Retrieval Augmented Generation (RAG)

include::./includes/attributes.adoc[]

When implementing Retrieval Augmented Generation (RAG), a robust document store is crucial. This guide demonstrates how to leverage a https://neo4j.com/[Neo4j] database as the document store.

IMPORTANT: Neo4j version 5.x or later is required (to support vector search).

== Leveraging the Neo4j embedding store

To make use of the Neo4j embedding store, you'll need to include the following dependency:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.langchain4j</groupId>
    <artifactId>quarkus-langchain4j-neo4j</artifactId>
</dependency>
----

The `quarkus-lanchain4j-neo4j` extension depends on another Quarkiverse
extension, https://github.com/quarkiverse/quarkus-neo4j[quarkus-neo4j],
which provides the Neo4j client capabilities and also Dev Services support.
All configuration from the `quarkus-neo4j` extension is thus applicable when
using a Neo4j database as the document store. See
https://docs.quarkiverse.io/quarkus-neo4j/dev/index.html[quarkus-neo4j
documentation] for more information.

NOTE: To get started, only one configuration property is required to be
set - `quarkus.langchain4j.neo4j.dimension`, which specifies the dimension
of the embeddings that you're going to store and depends on the embedding
model.

== Configuration Settings

Customize the behavior of the extension by exploring various configuration options:

include::includes/quarkus-langchain4j-neo4j.adoc[leveloffset=+1,opts=optional]
