= Pinecone Store for Retrieval Augmented Generation (RAG)

include::./includes/attributes.adoc[]

When implementing Retrieval Augmented Generation (RAG), a robust document store is crucial. This guide demonstrates how to leverage a https://www.pinecone.io/[Pinecone] database as the document store.

== Leveraging the Pinecone Document Store

To make use of the Pinecone document store, you'll need to include the following dependency:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.langchain4j</groupId>
    <artifactId>quarkus-langchain4j-pinecone</artifactId>
</dependency>
----

The required configuration properties to make the extension work are
`quarkus.langchain4j.pinecone.api-key`,
`quarkus.langchain4j.pinecone.environment`,
`quarkus.langchain4j.pinecone.index-name`, and
`quarkus.langchain4j.pinecone.project-id`. The specified index will be
created if it doesn't exist yet.

Upon installing the extension, you can utilize the Pinecone embedding store using the following code:

[source,java]
----
include::{examples-dir}/io/quarkiverse/langchain4j/samples/IngestorExampleWithPinecone.java[]
----

== Configuration Settings

Customize the behavior of the extension by exploring various configuration options:

include::includes/quarkus-langchain4j-pinecone.adoc[leveloffset=+1,opts=optional]
