= Hibernate ORM Embedding Store

include::./includes/attributes.adoc[]
include::./includes/customization.adoc[]

Quarkus LangChain4j integrates with Hibernate ORM to make use of databases supporting vector search for Retrieval-Augmented Generation (RAG).
This extension enables you to persist and query embedding vectors for document retrieval and is based on the https://docs.langchain4j.dev/integrations/embedding-stores/hibernate[LangChain4j Hibernate ORM integration].

== Prerequisites

To use Hibernate ORM as an Embedding store:

* A supported database with vector search capability is required.
* A Quarkus datasource must be configured.
* The embedding vector dimension must match your embedding model.

The currently supported databases are:

* DB2
* MariaDB
* MySQL Heatwave
* PostgreSQL with pgvector
* Oracle
* SQL Server

== Dependency

To enable the Hibernate ORM integration in your Quarkus project, add the following Maven dependency:

include::./includes/quarkus-langchain4j-maven-dependencies.adoc[provider-artifact=quarkus-langchain4j-hibernate]

This extension requires a configured Quarkus datasource and/or a Hibernate ORM persistence unit.
For configuration details, refer to the https://quarkus.io/guides/datasource[Quarkus DataSource Guide] and the https://quarkus.io/guides/hibernate-orm[Hibernate ORM Guide].

NOTE: Please beware that if you're using PostgreSQL, you have to make sure that the `pgvector` extension is available.
This can be done through Quarkus DevServices by configuring `quarkus.datasource.devservices.image-name=pgvector/pgvector:pg17`.

== Usage modes

In the "dynamic" mode you can use the provided `EmbeddingEntity` by configuring `quarkus.langchain4j.hibernate-orm-dynamic`
properties. This mode is useful to get started quickly, as well as when you don't want to do any data model customizations.

With the "custom" mode you can provide your own Hibernate ORM entity and configure `quarkus.langchain4j.hibernate-orm` properties,
or omit configuration altogether if your custom entity has an `@Embedding` annotated vector field.

== Embedding Dimension

You must explicitly configure the dimensionality of the embedding vector,
for the "dynamic" mode via:

[source,properties]
----
quarkus.langchain4j.hibernate-orm-dynamic.dimension=384
----

and for custom entities via the `@Array(length = ...)` annotation on the `@Embedding` annotated field.

This value depends on the embedding model in use:

* `AllMiniLmL6V2QuantizedEmbeddingModel` → 384
* OpenAI `text-embedding-ada-002` → 1536

[IMPORTANT]
====
If the embedding dimension is missing or mismatched, ingestion and retrieval will fail or produce inaccurate results.

If you switch to a different embedding model, ensure the `dimension` value is updated accordingly.
====

== Embedding Index

The "dynamic" mode allows you get started easily by creating vector indexes for you automatically.
Create-index controls whether the engine should create and use an index over the embeddings table.
To create an index, depending on your database, you might need the index-options parameter, which is a fine-tuning parameter.
On PostgreSQL with pgvector, if you set the `create-index=true` you will have to also set e.g. `index-options=lists=1`.

[NOTE]
====
This is something you rarely would need in development. 
====

[source,properties]
----
quarkus.langchain4j.hibernate-orm-dynamic.create-index=true
quarkus.langchain4j.hibernate-orm-dynamic.index-options=lists=10
----

Higher number of `lists` values speed up queries by reducing the search space during query time.
However, it also decreases the region size, which can lead to more recall errors by excluding some points.
Additionally, more distance comparisons are required to find the closest cluster during step one of the query process.

Here are some recommendations for setting the lists parameter:

* For datasets with less than one million rows, use lists = rows / 1000.
* For datasets with more than one million rows, use lists = sqrt(rows).
* It is generally advisable to have at least 10 clusters.

For details about index options configurations, please refer to the documentation of the respective database vendor.

When using a custom entity, please use schema management tools (like Liquibase or Flyway) to create your indexes.
Take a look into the https://docs.langchain4j.dev/integrations/embedding-stores/hibernate#5-custom-hibernate-entity-ddl[LangChain4j Hibernate ORM integration documentation]
for details about creating vector search indexes.

== Usage Example

Once the extension is installed and configured, you can ingest documents into your database using the following code:

[source,java]
----
include::{examples-dir}/io/quarkiverse/langchain4j/samples/IngestorExampleWithHibernate.java[]
----

This example shows how to embed and persist documents using the Hibernate ORM store, enabling efficient similarity search during RAG queries.
The default entity type that is used for `quarkus.langchain4j.hibernate-orm-dynamic` configurations is `EmbeddingEntity`.
Replace the type with your custom entity type when using the "custom" mode.

== Query Example

Assuming that data was ingested, one of the various `search` methods on the `HibernateEmbeddingStore` can be used
to search for matching entities.

[source,java]
----
include::{examples-dir}/io/quarkiverse/langchain4j/samples/QueryExampleWithHibernate.java[]
----

For further examples, take a look into the https://docs.langchain4j.dev/integrations/embedding-stores/hibernate#examples[LangChain4j Hibernate ORM documentation examples].

== Custom entity

When you want to customize the data model or want to reuse an existing entity as source for the `EmbeddingStore`,
you can make use of the annotations `@Embedding`, `@EmbeddedText`, `@UnmappedMetadata` and `@MetadataAttribute` to mark the
entity attributes to use by the Hibernate ORM `EmbeddingStore` implementation.

An embedding entity must at least specify an `@Embedding` attribute and an `@UnmappedMetadata` attribute.
You may specify an `@EmbeddedText` attribute if a single entity attribute is the source for the embedding vector,
but it is optional. Note that you require a `@EmbeddedText` attribute if you want to use metadata via the `TextSegment`
API that is exposed in the search result `EmbeddingMatch`, as well created during ingestion.

To map metadata to attributes/columns rather than JSON payload content, you can annotate entity attributes with `@MetadataAttribute`.
During ingestion, `TextSegment#metadata` attributes are mapped into dedicated entity attributes if possible,
while other metadata is stored in the `@UnmappedMetadata` entity attribute.

[source,java]
----
@Entity
public class MyEmbeddingEntity {
    @Id
    UUID id;
    @Embedding
    @Array(length = 384)                // The dimension of the embedding vector based on the embedding model
    float[] embedding;
    @EmbeddedText
    String text;
    @UnmappedMetadata
    Map<String, Object> metadata;       // Can be either a Map<String, Object> or a String

    @MetadataAttribute
    String mimeType;                    // Explicitly mapped. Synchronizes TextSegment#metadata with this attribute
    @MetadataAttribute
    String fileName;                    // Explicitly mapped. Synchronizes TextSegment#metadata with this attribute
}
----

If you don't specify any `quarkus.langchain4j.hibernate-orm` or `quarkus.langchain4j.hibernate-orm-dynamic` configuration,
the extension will try to find an entity containing a `@Embedding` annotation and use that and its containing
persistence unit for the embedding store.

NOTE: In development and test mode, the pgvector extension is automatically enabled (controlled via <<quarkus-langchain4j-hibernate-orm_quarkus-langchain4j-hibernate-orm-setup-vector-config,`quarkus.langchain4j.hibernate-orm.setup-vector-config`>>),
but keep in mind to enable the `vector` extension in your PostgreSQL database schema via `create extension if not exists vector;` with a schema management tool like Liquibase or Flyway.

== Configuration

Customize the behavior of the extension using the following configuration options:

include::includes/quarkus-langchain4j-hibernate.adoc[leveloffset=+1,opts=optional]

== How It Works

The Hibernate ORM extension maps each ingested document to an entity. Each entity contains:

* The original text content
* Optional metadata
* The vector embedding (stored as a `vector` type column)

During retrieval, a similarity search (e.g., cosine distance) is performed using a `SELECT` query with `ORDER BY embedding +<=>+ :query_vector FETCH FIRST N ROWS ONLY`.

== Comparison with quarkus-langchain4j-pgvector extension

The Quarkus LangChain4j Hibernate ORM extension provides similar features to the Quarkus LangChain4j pgvector extension
and can also be used with pgvector on PostgreSQL.

The major difference is that the Quarkus LangChain4j Hibernate ORM extension is implemented through Hibernate ORM APIs,
which abstract away the data store details. This extension can thus also be used with other supported data stores.

== Summary

To use Hibernate ORM as an embedding store with Quarkus LangChain4j:

* Ensure your database is configured correctly for vector search.
* Add the extension dependency.
* Configure a datasource and set the correct embedding dimension.
* Use `HibernateEmbeddingStore` to ingest and retrieve embedded documents.

