= Using web search

Quarkus LangChain4j currently supports the https://tavily.com/[Tavily] search engine.
To use it, add the `quarkus-langchain4j-tavily` extension to your project. You'll need to specify the API key, this is done by the `quarkus.langchain4j.tavily.api-key` property.

After this, you can inject the search engine into your application using

[source,java]
----
@Inject
WebSearchEngine engine;
----

and then use it by calling its `search` method.

If you want to let a chat model use web search by itself, there are
generally two recommended ways to accomplish this: either by implementing a
tool that uses it, or as a content retriever inside a RAG pipeline. The
https://github.com/quarkiverse/quarkus-langchain4j/tree/main/samples/chatbot-web-search[chatbot-web-search]
example in the `quarkus-langchain4j` repository demonstrates using web
search as a tool.

== Using Web search as a tool

To use web search as a tool that the LLM can decide to execute (and the
relevant search results will be the return value of the tool execution), you
can either use the provided tool from the upstream LangChain4j project,
in class `dev.langchain4j.web.search.WebSearchTool`, or implement your own tool
if that one does not fit your requirements. The `samples/chatbot-web-search`
example demonstrates how to use the provided tool.

== Using Web search in a RAG pipeline

There is also a provided content retriever, `dev.langchain4j.rag.content.retriever.WebSearchContentRetriever` that uses
a web search engine to retrieve relevant documents.
For inspiration, the retrieval augmentor that wraps it may look like this:

[source,java]
----
@ApplicationScoped
public class WebSearchRetrievalAugmentor implements Supplier<RetrievalAugmentor> {

    @Inject
    WebSearchEngine webSearchEngine;

    @Inject
    ChatLanguageModel chatModel;

    @Override
    public RetrievalAugmentor get() {
        return DefaultRetrievalAugmentor.builder()
                .queryTransformer((question) -> {
                    // before actually querying the engine, we need to transform the
                    // user's question into a suitable search query
                    String query = chatModel.generate("Transform the user's question into a suitable query for the " +
                            "Tavily search engine. The query should yield the results relevant to answering the user's question." +
                            "User's question: " + question.text());
                    return Collections.singleton(Query.from(query));
                }).contentRetriever(new WebSearchContentRetriever(webSearchEngine, 10))
                .build();
    }
}
----

== Tavily configuration reference

include::includes/quarkus-langchain4j-tavily.adoc[leveloffset=+1,opts=optional]
