services:
  mongodb:
    image: mongodb/mongodb-atlas-local:latest
    ports:
      - "27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
