#!/usr/bin/env bash
# Regenerates every SVG in modules/ROOT/assets/images/ from its Mermaid
# source in diagrams/. Run via: npm run diagrams
#
# The mermaid-config.json (useMaxWidth: false) is required so each SVG
# gets explicit pixel width/height attributes. Without them the browser
# treats the SVG as having no intrinsic width and stretches it to the
# full docs column, making narrow diagrams disproportionately large.
#
# Generated by Claude Code
set -euo pipefail
cd "$(dirname "$0")/.."

for src in diagrams/*.mmd; do
  name=$(basename "$src" .mmd)
  out="modules/ROOT/assets/images/$name.svg"
  echo "Rendering $src -> $out"
  npx mmdc -i "$src" -o "$out" -c diagrams/mermaid-config.json -b white --quiet
  # Mark the output as generated so nobody edits it by hand.
  sed -i "1s|<svg |<!-- Generated from diagrams/$name.mmd; do not edit directly. Regenerate with: npm run diagrams --><svg |" "$out"
done
