quarkus.langchain4j.embedding-model.provider=dev.langchain4j.model.embedding.onnx.allminilml6v2.AllMiniLmL6V2EmbeddingModel
quarkus.langchain4j.openai.api-key=blabla

quarkus.langchain4j.lancedb.api-key=${LANCEDB_API_KEY}
quarkus.langchain4j.lancedb.database=${LANCEDB_DATABASE:test-db}
quarkus.langchain4j.lancedb.dimension=384
quarkus.langchain4j.lancedb.distance-type=cosine
