package io.quarkiverse.langchain4j.infinispan.runtime;

import java.util.Optional;

import io.quarkus.runtime.annotations.ConfigGroup;
import io.smallrye.config.WithDefault;

/**
 * Configuration for a single Infinispan embedding store instance.
 */
@ConfigGroup
public interface InfinispanStoreRuntimeConfig {

    /**
     * The dimension of the embedding vectors. This has to be the same as the dimension of vectors produced by
     * the embedding model that you use. For example, AllMiniLmL6V2QuantizedEmbeddingModel produces vectors of dimension 384.
     * OpenAI's text-embedding-ada-002 produces vectors of dimension 1536.
     */
    Long dimension();

    /**
     * Name of the cache that will be used in Infinispan when searching for related embeddings.
     * If this cache doesn't exist, it will be created.
     */
    @WithDefault("embeddings-cache")
    String cacheName();

    /**
     * The maximum distance. The most distance between vectors is how close or far apart two embeddings are.
     */
    @WithDefault("3")
    Integer distance();

    /**
     * The similarity metric to use for vector search.
     * Supported values: COSINE, L2, INNER_PRODUCT, MAX_INNER_PRODUCT.
     */
    @WithDefault("COSINE")
    String similarity();

    /**
     * Whether to create the cache on startup if it does not exist.
     * Set to false if the cache is pre-configured on the Infinispan server.
     */
    @WithDefault("true")
    boolean createCache();

    /**
     * Optional full XML or JSON cache configuration.
     * When provided, this overrides the default cache configuration generated by the extension.
     */
    Optional<String> cacheConfig();
}
