# Apicurio Registry
quarkus.langchain4j.a2a.apicurio-registry.url=http://localhost:8080/apis/registry/v3
quarkus.langchain4j.a2a.apicurio-registry.agent-url=http://localhost:8090

# Ollama
quarkus.langchain4j.ollama.chat-model.model-id=llama3.2

# Logging
quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true
quarkus.log.category."io.quarkiverse.langchain4j.a2a".level=DEBUG
