name: Build against LangChain4j main

on:
  schedule:
    - cron: '0 2 * * 1-5'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build on ${{ matrix.os }} - ${{ matrix.java }}
    strategy:
      # PineconeEmbeddingStoreTest uses a single shared index, we can't run multiple CI runs on it at once
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [17, 21]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false
        if: startsWith(matrix.os, 'windows')

      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build langchain4j
        run: |
          git clone https://github.com/langchain4j/langchain4j.git
          cd langchain4j
          ./mvnw -B clean install -DskipTests -DskipITs

      - name: Build with Maven
        run: |
          LANGCHAIN4J_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f langchain4j/pom.xml)
          echo "LANGCHAIN4J_VERSION=$LANGCHAIN4J_VERSION"
          ./mvnw -B clean install -Dno-format -Dlangchain4j.version=$LANGCHAIN4J_VERSION
        env:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
          PINECONE_INDEX_NAME: ${{ secrets.PINECONE_INDEX_NAME }}
          PINECONE_PROJECT_ID: ${{ secrets.PINECONE_PROJECT_ID }}

#      - name: Build with Maven (Native)
#        run: ./mvnw -B install -Dnative -Dquarkus.native.container-build -Dnative.surefire.skip
#        env:
#          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
#          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
#          PINECONE_INDEX_NAME: ${{ secrets.PINECONE_INDEX_NAME }}
#          PINECONE_PROJECT_ID: ${{ secrets.PINECONE_PROJECT_ID }}
