kind: Secret
apiVersion: v1
metadata:
  name: anthropic-wif
  namespace: workload-identity-spiffe
type: Opaque
stringData:
  ANTHROPIC_FEDERATION_RULE_ID: <your-federation-rule-id>
  ANTHROPIC_ORGANIZATION_ID: <your-organization-id>
  ANTHROPIC_SERVICE_ACCOUNT_ID: <your-service-account-id>
